name: Check pull request

on:
  pull_request:
    branches: [ release ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name:   Checkout branch
      uses:   actions/checkout@v3

    - name: Build test Docker image
      run:  docker build -t local --target test .

    - name:   Run tests
      run:    docker run --rm local