name: Check pull request

on:
  pull_request:
    branches: [ release ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name:   Checkout branch
      uses:   actions/checkout@v3

    - name:   Set up Docker Buildx
      uses:   docker/setup-buildx-action@v2

    - name:   Build test Docker image
      tags:   zetkoofficial/network_status:latest
      target: test
      
    - name:   Run tests
      run:    docker run --rm zetkoofficial/network_status:latest